### ISSUE TITLE
Can't get In E2E with memory to work

### ISSUE THREAD

**Issue by mbeckenbach** [garbados/comdb#13] opened 2021-05-02 16:24 UTC
Hi, 

tanks for this awesome lib!

I am trying to get the e2e encryption working in an angular 10 app. Just like you showed it here:
https://github.com/garbados/comdb/issues/4

But i have trouble with the pouchdb-adapter-memory.

When I import it as this:
```
import PouchDB from 'pouchdb'; // Works
import PouchAuth from 'pouchdb-authentication'; // Works
import comdb from 'comdb'; // Works
import PouchMemory from 'pouchdb-adapter-memory'; // Does not

PouchDB.plugin(PouchAuth);
PouchDB.plugin(comdb);
PouchDB.plugin(PouchMemory);
```

I get this at app start: 
```
Error: ./node_modules/sublevel-pouchdb/node_modules/readable-stream/readable.js
Module not found: Error: Can't resolve 'stream' in 'C:\source\ngcp\node_modules\sublevel-pouchdb\node_modules\readable-stream
'``

Then I tried to import this: 

```
import PouchMemory from 'pouchdb/dist/pouchdb.memory';
```

and got
```
memory adapter plugin error: Cannot find global "PouchDB" object! Did you remember to include pouchdb.js?
core.js:6210 ERROR Error: Invalid plugin: got "[object Object]", expected an object or a function
```

I simply don't get it. Do you have any idea? I would be very thankful.
Btw. what I actually try to accomplish in the end is storing data encrypted on the client while having the decrypted version on the server. :-)

**Comment by garbados** [comment] 2021-05-06 17:17
Have you installed pouchdb-adapter-memory as a dependency?

**Comment by garbados** [comment] 2021-05-06 17:20
It's hard for me to guess what's going wrong since I'm not familiar with Angular (not since a much earlier version). It might be that your compilation process doesn't know what to do with pouchdb-adapter-memory's implementation. It was last modified [around 2017](https://github.com/pouchdb/pouchdb/tree/master/packages/node_modules/pouchdb-adapter-memory) so it might reflect some older conventions that cause more recent tools to choke. If you can isolate a bug, I'd be happy to file the issue and follow up on it.

**Comment by garbados** [comment] 2021-05-06 17:21
Furthermore, I've detected some bugs in this E2E approach using ComDB that I am still working to resolve. I'm glad you find this library useful, but be warned it is still rather experimental.

**Comment by jjtolton** [comment] 2021-12-20 22:03
Hi @garbados !  Curious what the status on this is and if you have any plans to tinker with it any further?  I wasn't able to get any of the encryption/reload recipes to work. 

```javascript
var PASSWORD = "blahzeblaht";
const db = new PouchDB("local");
db.setPassword(PASSWORD).then(async () => { 
  await db.loadEncrypted();
});
```
I then execute:
`await db.post({name: 'bob'})`
and that works ok.  

then 
`await db.allDocs({include_docs: true})` 
returns the expected results.  However, when I reload the page, I get this error:

![image](https://user-images.githubusercontent.com/10394611/146838353-fd26842e-34b8-4955-b3d6-41b2595187ed.png)

If I try the same experiment but with adapter='memory', 

```javascript


// db already exists, we are just adding encryption
var PASSWORD = "blahzeblaht";
const db = new PouchDB("local3",  {adapter: "memory"});

db.setPassword(PASSWORD).then(async () => { 
  await db.loadEncrypted();
});
```
I get 
![image](https://user-images.githubusercontent.com/10394611/146838583-04cbf8c2-42c2-4866-ba4d-18a16bd2f108.png)

I tried tinkering with the source code a little bit but didn't get anywhere.  Curious if you had any insight.

**Comment by garbados** [comment] 2022-03-21 18:54
Hi @jjtolton ! I'll look into your issue and see if I can't reproduce it. But yeah, my open source contributions outside of work are pretty limited these days.

**Comment by jjtolton** [comment] 2022-03-23 12:22
If it needs to be a paid thing to help move this along let me know.  Setup
a GitHub sponsors page or send me an email ***@***.***!  Happy to
contribute.

**Comment by garbados** [comment] 2022-04-24 17:48
Hi @jjtolton ! I'm in the process of setting up a GitHub Sponsors account. In the meantime, I'm taking a look at this today.

**Comment by jjtolton** [comment] 2022-04-24 18:00
Thanks so much!  Looking forward to testing, this is a great project.

**Comment by garbados** [comment] 2022-04-24 18:39
OK. I'm able to reproduce the bug. It seems the document revision isn't being appropriately tied back to a document after its creation if it was created with `post()`. I have a fix locally and I'm writing a test to verify.

**Comment by garbados** [comment] 2022-04-24 19:26
Hi @jjtolton ! I've isolated your particular issue [here](https://github.com/garbados/comdb/issues/21) and pushed a fix [here](https://github.com/garbados/comdb/pull/22). I'll be closing this issue as it doesn't look like the OP is coming back.

**Closed by garbados** 2022-04-24 19:26 UTC
